# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=500, unique=True)),
                ('host_port', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinLengthValidator(10000), django.core.validators.MaxLengthValidator(22000)])),
                ('build', models.BooleanField(default=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.LessonsLearningStylesResources')),
            ],
            options={
                'verbose_name_plural': 'Docker Containers',
            },
        ),
    ]
