# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('learning_styles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('description', models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('logo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Resources')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('description', models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses')),
            ],
            options={
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonsLearningStylesResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('description', models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('learning_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_styles.LearningStyles')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lessons')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.Resources')),
            ],
            options={
                'verbose_name_plural': 'Lessons Learning Style Resources',
            },
        ),
        migrations.CreateModel(
            name='UserLessonsCompleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course Progress',
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='resources',
            field=models.ManyToManyField(max_length=500, related_name='resources', through='courses.LessonsLearningStylesResources', to='learning_styles.LearningStyles'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='user_progress',
            field=models.ManyToManyField(through='courses.UserLessonsCompleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lessons',
            unique_together=set([('course', 'sequence_number')]),
        ),
    ]
