# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=resources.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
